### ISSUE TITLE
Auf untersagte Nutzung durch Mitarbeiter:innen hinweisen

### ISSUE THREAD

**Issue by MorMundHS-MA** [informatik-mannheim/HSMA-CTT#135]
Da Mitarbeiter:innen durch den Personalrat aus Datenschutz gründen die Anwendung nicht nutzen dürfen sollte in der Anwendung darauf hingewiesen werden.

- [x] auf <https://ctt.hs-mannheim.de/datenschutz>
- [x] auf den Ausdrucken
- [x] Im Check-In bei Auswahl von "Mitarbeiter:in", dafür einen extra Auswahlpunkt Lehrende?

**Comment by Wifi-cable** [comment]
Text "Nicht für Mitarbeitende" reicht.  Oder "Nicht für Mitarbeiter:inen", "Nicht für MitarbeiterInnen"  (Ich bin weder Expertin für Rechtschreibung noch dafür welche Form des Genderns die Schönste ist.  Es darf in kleiner Schrift sein. Es muss auch nicht begründet werden.

**Comment by MorMundHS-MA** [comment]
Closed in #142
