### ISSUE TITLE
RoomController /checkOut should not send empty email request

### ISSUE THREAD

**Issue by L4trax** [informatik-mannheim/HSMA-CTT#155]
if the mail form is empty it should not be sent to the backend for further validation.

**Comment by oliverhummel** [comment]
pls check whether this is still relevant? I am not sure which mail form is meant.

**Comment by maxones25** [comment]
The mail form contains only one hidden input field. If the value of the field is empty, an error has already occurred before. The backend checks if an email address was submitted. I would close the issue.
