### ISSUE TITLE
End of day auto checkout never runs

### ISSUE THREAD

**Issue by MorMundHS-MA** [informatik-mannheim/HSMA-CTT#159]
The task that checks people at the end of the day currently never runs, see #157.

Things that need to happen for a fix:

- [ ] Remove the condition that only allows the task to run after 21:00 (because it gets run at 3:59 in the morning, which is always before the condition is true ...)
- [ ] Ensure the `checkOutAllVisitors` [link](https://github.com/informatik-mannheim/HSMA-CTT/blob/3f99f4f4f83d080da88ab2d2223a9a7f33a85f0a/src/main/java/de/hs_mannheim/informatik/ct/persistence/services/RoomVisitService.java#L118) method correctly checks out people, especially when run at 3:59. It probably doesn't work when run on the same day as people checked-in.
- [ ] Write test-cases, especially for the 3:59 case.
- [ ] Remove the db hotfix. Replace rows with manually set checkout reason of `999` with empty reason and end time of `null`. Ensure on a local copy that these rows are correctly fixed by the auto checkout logic.

**Comment by oliverhummel** [comment]
As of today, this still does not work properly, although there is no exception in the logs anymore.

**Comment by oliverhummel** [comment]
done
