### ISSUE TITLE
Removal of old entries doesn't work

### ISSUE THREAD

**Issue by MorMundHS-MA** [informatik-mannheim/HSMA-CTT#160]
See [this comment](https://github.com/informatik-mannheim/HSMA-CTT/issues/157#issuecomment-884024055).

- [ ] Write a test case confirming the bug 
- [ ] OR check if the issue is caused by the removal task not running at all

**Comment by oliverhummel** [comment]
Problems have been caused by old data in DB and seem to be resolved after clearing that. 

However, we should make sure, that old data does not interrupt our nightly purge.

**Comment by Wifi-cable** [comment]
Issue seems to persist at times. Auto Checkout not working?

**Comment by oliverhummel** [comment]
done
