### ISSUE TITLE
Raumpinn eingabe verwirrt Nutzer

### ISSUE THREAD

**Issue by Wifi-cable** [informatik-mannheim/HSMA-CTT#163]
Wenn Nutzer die Raumpin nicht eingeben werden sie auf die Startseite umgeleitet mit einer "Fehler-Code: 400" Meldung. Das scheint sie zu verwirren, denn sie verstehen den Zusammenhang zu nicht ausgefüllten Felder nicht. Statt die Pin einzugeben schicken sie uns Bug Reports.

**Comment by L4trax** [comment]
fixed with new Exceptionandler
