### ISSUE TITLE
Sandbox Raum (dummy)

### ISSUE THREAD

**Issue by Wifi-cable** [informatik-mannheim/HSMA-CTT#165]
Priorität: niedrig.
Viele Nutzer sind so neugierig das sie das CTT ausprobieren/testen wollen.  Das produziert komische Daten wenn alle das machen. 

Vorschlag:  wir legen einen "Sandboxraum" an. Ein  Raum den es an der HS nicht gibt, der nicht in der Kontaktverfolgung ist, zu dem es aber zwei QR Codes gibt (Veranstaltungsleitende und Teilnehmende) 

Sollten wir den Nuztern noch etwas anderes zu "spielen" geben?

**Comment by oliverhummel** [comment]
Gute Idee, dessen QRCode könnte man dann auf der Startseite verlinken, so dass die Leute das von einem Rechner aus ausprobieren können.

**Comment by Wifi-cable** [comment]
Should this not tracked sandbox room have a different type in "room types"?
