### ISSUE TITLE
Add line to every Login specifiying who can log into the System. (Users are confused)

### ISSUE THREAD

**Issue by Wifi-cable** [informatik-mannheim/HSMA-CTT#204]
- [ ] Specify that the login is for "contact tracers" (Kontaktverfolgung, Hyienebeautfragte)  to prevent Professors from wondering why their University login does not help.
- [ ]  Specify that login for event creation (Veranstaltungen)   is for admin use. Professors and students do not need to login to this portal to use the web-app

**Comment by oliverhummel** [comment]
Maybe we should remove the login link completely? As the login page appear anyway when Kontaktverfolgung is selected?

**Comment by Wifi-cable** [comment]
I agree that the login for creating events is  currently not needed, unless we assign the role "event-creator" to someone. Removing the menu item and the routing for this will improve usability.

Labeling the login for the contact tracer with a line of code still makes sense.  Less confusion for users who believe they need to log in to services, because they always logged into university services.
