### ISSUE TITLE
comment out 3G status Check

### ISSUE THREAD

**Issue by Wifi-cable** [informatik-mannheim/HSMA-CTT#226]
comment out or remove method preventing privileged checkout without having set the "I have checked that everyone is imune or negative" .

Remove the checkbox and filed from front-end. (replace with gray box maybe?)

**Comment by oliverhummel** [comment]
Commenting out is done, however, in the medium term, it would be nice to have this configurable with a parameter.

**Comment by maxones25** [comment]
the 3G is now configurable via environement variable 'check_3G_status'
PR: #258
