### ISSUE TITLE
Raum Reset ermöglichen (für alle Mitarbeiter der hs)

### ISSUE THREAD

**Issue by hsmagit** [informatik-mannheim/HSMA-CTT#88]
Es muss eine Möglichkeit geben **alle** Personen aus dem Raum auszuchecken

- [ ] Nutzer muss gewarnt werden  was passiert
- [ ] Nutzer kann die Warnung nur schließen, wenn er bestätigt, dass er sich im klaren ist was er da macht
- [ ] Hinweis auf Rechtliche Folgen bei Missbrauch

**Comment by oliverhummel** [comment]
Letzte Idee: 
Extra-QR-Code (auf einem Zettel mit anderer Farbe), der die Raumbelegung des aktuellen Raums zeigt (mit Knopf, um einen Reload auszulösen o. ggf. auch Autor-Refresh)
Und dort dann die Möglichkeit, den Raum zu resetten (vorerst ohne spezielle Passwörter o.ä., IP mit Speichern?)

**Comment by MorMundHS-MA** [comment]
Closed in favor of a new meta issue #125
